apiVersion: v1
kind: Service
metadata:
  name: media-services
  namespace: media
spec:
  type: NodePort
  selector:
    app: media-services
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30096  # Updated port
  - protocol: TCP
    port: 8989
    targetPort: 8989
    nodePort: 30089

