---
# my-sonarr-values.yaml

image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    - name: http
      enabled: true
      port: 8989
      nodePort: 30081  # Must be between 30000-32767 and unused
    - name: https
      enabled: false
      port: 443
      nodePort: 30443  # Optional: Only if you plan to enable HTTPS in the future

ingress:
  enabled: false  # Disable Ingress if you're using NodePort

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 5Gi
    mountPath: /config
    accessModes:
      - ReadWriteOnce

  data:
    enabled: true
    storageClass: local-path
    size: 10Gi
    mountPath: /downloads
    accessModes:
      - ReadWriteOnce

  media:
    enabled: true
    existingClaim: jellyfin-media-pvc
    mountPath: /media

environment:
  - name: PUID
    value: '1000'  # Replace with the UID of the user running Sonarr (e.g., jellyfin)
  - name: PGID
    value: '1000'  # Replace with the GID of the group running Sonarr (e.g., jellyfin)
  - name: TZ
    value: 'America/New_York'

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
# Optional: Add any additional environment variables or configurations as needed
