---
image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    http:
      enabled: true
      port: 8989
      nodePort: 30081

ingress:
  enabled: false

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 5Gi
    mountPath: /config
    accessModes:
      - ReadWriteOnce

  data:
    enabled: true
    storageClass: local-path
    size: 10Gi
    mountPath: /downloads
    accessModes:
      - ReadWriteOnce
    accessMode: ReadWriteOnce

  media:
    enabled: true
    existingClaim: jellyfin-media-pvc
    mountPath: /media

environment:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: 'America/New_York'
