apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      hostNetwork: true
      hostname: jellyseerr
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          ports:
            - containerPort: 5055
              protocol: TCP
          env:
            - name: TZ
              value: America/Montreal
          volumeMounts:
            - name: jellyseerr-config
              mountPath: /app/config
      volumes:
        - name: jellyseerr-config
          hostPath:
            path: /srv/media/Jellyseerr/config
            type: DirectoryOrCreate
