apiVersion: apps/v1
kind: Deployment
metadata:
  name: nordvpn
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nordvpn
  template:
    metadata:
      labels:
        app: nordvpn
    spec:
      containers:
        - name: nordvpn
          image: dperson/openvpn-client
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: username
            - name: OPENVPN_PASS
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: password
          args:
            - '-f'
            - '-c'
            - '/vpn/nordvpn.ovpn'
            - '--verb'
            - '3'
          volumeMounts:
            - name: vpn-config
              mountPath: '/vpn'
          resources:
            requests:
              cpu: '100m'
              memory: '50Mi'
            limits:
              cpu: '500m'
              memory: '200Mi'
      volumes:
        - name: vpn-config
          configMap:
            name: nordvpn-config
---
apiVersion: v1
kind: Service
metadata:
  name: nordvpn
  namespace: media
spec:
  selector:
    app: nordvpn
  ports:
    - name: dummy
      protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP
