apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-client
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn-client
      vpn: nordvpn
  template:
    metadata:
      labels:
        app: openvpn-client
        vpn: nordvpn
    spec:
      volumes:
        - name: vpn-config
          configMap:
            name: vpn-config
            items:
              - key: client.ovpn
                path: client.ovpn
        - name: vpn-auth
          secret:
            secretName: vpn-auth
            items:
              - key: auth.txt
                path: auth.txt
        - name: route-script
          configMap:
            name: route-script
            items:
              - key: route-override.sh
                path: route-override.sh
        - name: tmp
          emptyDir: {}
      initContainers:
        - name: vpn-route-init
          image: busybox
          command:
            - /bin/sh
            - -c
            - 'mkdir -p /tmp/route && cp /vpn/route-override.sh /tmp/route/route-override.sh && chmod +x /tmp/route/route-override.sh'
          volumeMounts:
            - name: tmp
              mountPath: /tmp/route
            - name: route-script
              mountPath: /vpn/route-override.sh
              subPath: route-override.sh
      containers:
        - name: vpn
          image: dperson/openvpn-client
          command: ['/bin/sh', '-c']
          args:
            - "openvpn --config 'vpn/client.ovpn' --auth-user-pass 'vpn/auth.txt' --script-security 3 --route-up /tmp/route/route-override.sh; sleep infinity"
          tty: true
          stdin: true
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: vpn-config
              mountPath: /vpn/client.ovpn
              subPath: client.ovpn
            - name: vpn-auth
              mountPath: /vpn/auth.txt
              subPath: auth.txt
            - name: tmp
              mountPath: /tmp/route
          env:
            - name: TZ
              value: 'UTC'
        - name: socks-proxy
          image: dperson/socks5:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  name: openvpn-socks
  namespace: media
spec:
  selector:
    app: openvpn-client
  ports:
    - name: socks
      protocol: TCP
      port: 1080
      targetPort: 1080
  type: ClusterIP
