apiVersion: apps/v1
kind: Deployment
metadata:
  name: nordvpn
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nordvpn
  template:
    metadata:
      labels:
        app: nordvpn
    spec:
      containers:
      - name: nordvpn
        image: dperson/openvpn-client
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: nordvpn-credentials
              key: username
        - name: OPENVPN_PASS
          valueFrom:
            secretKeyRef:
              name: nordvpn-credentials
              key: password
        args:
        - "-f"
        - "--config"
        - "/vpn-config/nordvpn.ovpn"
        volumeMounts:
        - name: vpn-config
          mountPath: "/vpn-config"
      volumes:
      - name: vpn-config
        configMap:
          name: nordvpn-config
---
apiVersion: v1
kind: Service
metadata:
  name: nordvpn
  namespace: media
spec:
  selector:
    app: nordvpn
  type: ClusterIP
