apiVersion: apps/v1
kind: Deployment
metadata:
  name: nordvpn
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nordvpn
  template:
    metadata:
      labels:
        app: nordvpn
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.rp_filter
            value: '2'
      containers:
        - name: nordvpn
          image: dperson/openvpn-client
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: openvpn-credentials
                  key: username
            - name: OPENVPN_PASS
              valueFrom:
                secretKeyRef:
                  name: openvpn-credentials
                  key: password
          args:
            - '-f'
            - '--config'
            - '/vpn-config/ca1638.nordvpn.com.udp.ovpn'
            - '--verb'
            - '3'
          volumeMounts:
            - name: vpn-config
              mountPath: '/vpn-config'
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 200Mi
      volumes:
        - name: vpn-config
          configMap:
            name: nordvpn-config
---
apiVersion: v1
kind: Service
metadata:
  name: nordvpn
  namespace: media
spec:
  selector:
    app: nordvpn
  type: ClusterIP
  ports:
    - name: dummy
      protocol: TCP
      port: 9999
      targetPort: 9999
